[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/return.html"
  to = "/return.html"
  status = 200
  force = true
  method = "POST"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
